# This workflow uses actions that are not certified by GitHub.
# São fornecidas por terceiros e regidas por
# termos de serviço, política de privacidade e suporte separados
# documentação.

name: Fullstack CI

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main

jobs:
  build-back:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Change wrapper permissions
        working-directory: ./backend
        run: chmod +x ./gradlew
      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew build

  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: ./frontend
        run: npm i
      - name: Run lint
        working-directory: ./frontend
        run: npm run ng lint
      - name: Run test
        working-directory: ./frontend
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: Run integration test
        working-directory: ./frontend
        run: |
          npm run e2e
